# Generated by Django 5.1.1 on 2025-02-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='value',
            field=models.IntegerField(),
        ),
    ]
