# Generated by Django 5.2.4 on 2025-11-11 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_passwordresetcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborativeCalendarGroup',
            fields=[
                ('share_group_id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='群组ID')),
                ('share_group_name', models.CharField(max_length=200, verbose_name='群组名称')),
                ('share_group_color', models.CharField(default='#3498db', max_length=20, verbose_name='颜色标签')),
                ('share_group_description', models.TextField(blank=True, verbose_name='群组描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_share_groups', to=settings.AUTH_USER_MODEL, verbose_name='群主')),
            ],
            options={
                'verbose_name': '协作日历群组',
                'verbose_name_plural': '协作日历群组',
                'db_table': 'collaborative_calendar_group',
            },
        ),
        migrations.CreateModel(
            name='GroupCalendarData',
            fields=[
                ('share_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='calendar_data', serialize=False, to='core.collaborativecalendargroup', verbose_name='所属群组')),
                ('events_data', models.JSONField(default=list, verbose_name='事件数据')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('version', models.IntegerField(default=0, verbose_name='版本号')),
            ],
            options={
                'verbose_name': '群组日历数据',
                'verbose_name_plural': '群组日历数据',
                'db_table': 'group_calendar_data',
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '群主'), ('admin', '管理员'), ('member', '成员')], default='member', max_length=20, verbose_name='角色')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('share_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.collaborativecalendargroup', verbose_name='所属群组')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='成员用户')),
            ],
            options={
                'verbose_name': '群组成员',
                'verbose_name_plural': '群组成员',
                'db_table': 'group_membership',
                'ordering': ['-joined_at'],
                'unique_together': {('share_group', 'user')},
            },
        ),
    ]
