# Generated by Django 5.2.4 on 2025-11-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_collaborativecalendargroup_groupcalendardata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='member_color',
            field=models.CharField(default='#3498db', max_length=20, verbose_name='成员个人颜色'),
        ),
    ]
