# Generated by Django 6.0.2 on 2026-03-28 08:28

import django.db.models.deletion
import file_service.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='文件夹名称', max_length=255)),
                ('path', models.CharField(db_index=True, help_text='物化路径，如 /文档/工作/', max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='file_service.userfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户文件夹',
                'verbose_name_plural': '用户文件夹',
                'ordering': ['path'],
                'unique_together': {('user', 'path')},
            },
        ),
        migrations.CreateModel(
            name='UserStorageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_storage_bytes', models.BigIntegerField(default=267386880, help_text='存储空间上限（字节），默认 255MB')),
                ('max_file_size', models.BigIntegerField(default=20971520, help_text='单文件大小上限（字节），默认 20MB')),
                ('used_bytes', models.BigIntegerField(default=0, help_text='已用存储空间（字节）')),
                ('file_count', models.IntegerField(default=0, help_text='文件总数')),
                ('tier', models.CharField(choices=[('free', '免费版'), ('basic', '基础版'), ('pro', '专业版'), ('enterprise', '企业版')], default='free', help_text='用户存储等级（预留付费扩容）', max_length=20)),
                ('tier_expires_at', models.DateTimeField(blank=True, help_text='付费等级到期时间', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户存储配额',
                'verbose_name_plural': '用户存储配额',
            },
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(help_text='原始文件', upload_to=file_service.storage.user_file_upload_to)),
                ('filename', models.CharField(help_text='用户可见的文件名', max_length=512)),
                ('file_size', models.BigIntegerField(default=0, help_text='文件大小（字节）')),
                ('mime_type', models.CharField(help_text='MIME 类型', max_length=100)),
                ('category', models.CharField(choices=[('document', '文档'), ('image', '图片')], help_text='文件分类', max_length=20)),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 文件哈希，用于去重', max_length=64)),
                ('parsed_markdown', models.TextField(blank=True, default='', help_text='预解析的 Markdown 内容')),
                ('parsed_at', models.DateTimeField(blank=True, help_text='解析完成时间', null=True)),
                ('parse_status', models.CharField(choices=[('none', '无需解析'), ('pending', '待解析'), ('processing', '解析中'), ('completed', '已完成'), ('failed', '解析失败')], default='pending', help_text='解析状态', max_length=20)),
                ('parse_source', models.CharField(blank=True, default='', help_text='解析来源：baidu_cloud / local_fallback / reused / reused_from_attachment / none', max_length=30)),
                ('parse_error', models.TextField(blank=True, default='', help_text='解析错误信息')),
                ('markdown_edited', models.BooleanField(default=False, help_text='用户是否手动编辑过 Markdown')),
                ('text_preview', models.CharField(blank=True, default='', help_text='前 500 字摘要', max_length=500)),
                ('search_text', models.TextField(blank=True, default='', help_text='去除 MD 格式的纯文本，用于全文检索')),
                ('source', models.CharField(choices=[('upload', '本地上传'), ('url', 'URL上传'), ('chat_upload', '聊天上传')], default='upload', help_text='上传来源', max_length=20)),
                ('source_url', models.URLField(blank=True, default='', help_text='URL 上传时的原始地址', max_length=2048)),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已软删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_files', to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='file_service.userfolder')),
            ],
            options={
                'verbose_name': '用户文件',
                'verbose_name_plural': '用户文件',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'folder', 'is_deleted'], name='file_servic_user_id_598cc2_idx'), models.Index(fields=['user', 'category', 'is_deleted'], name='file_servic_user_id_4ac16c_idx'), models.Index(fields=['user', 'is_deleted', '-created_at'], name='file_servic_user_id_c504c9_idx'), models.Index(fields=['file_hash'], name='file_servic_file_ha_a4b09e_idx')],
            },
        ),
    ]
