# Generated by Django 5.2.4 on 2025-12-20 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memoryitem',
            options={'ordering': ['-importance', '-created_at']},
        ),
        migrations.AddField(
            model_name='memoryitem',
            name='category',
            field=models.CharField(default='general', help_text='类别 (preference, fact, plan, general)', max_length=50),
        ),
        migrations.AddField(
            model_name='memoryitem',
            name='importance',
            field=models.IntegerField(default=1, help_text='重要性 (1-5)'),
        ),
        migrations.AddField(
            model_name='memoryitem',
            name='memory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='agent_service.usermemory'),
        ),
        migrations.CreateModel(
            name='AgentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='会话 ID', max_length=200)),
                ('action_type', models.CharField(help_text='操作类型 (create_event, delete_todo, etc.)', max_length=100)),
                ('revision_id', models.IntegerField(blank=True, help_text='django-reversion 的 Revision ID', null=True)),
                ('metadata', models.JSONField(default=dict, help_text='额外的元数据')),
                ('is_rolled_back', models.BooleanField(default=False, help_text='是否已回滚')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent 事务',
                'verbose_name_plural': 'Agent 事务',
                'ordering': ['-created_at'],
            },
        ),
    ]
