# Generated by Django 5.2.4 on 2025-12-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_service', '0002_alter_memoryitem_options_memoryitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttransaction',
            name='description',
            field=models.TextField(blank=True, default='', help_text='操作描述'),
        ),
    ]
