# Generated by Django 5.2.4 on 2025-12-21 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_service', '0003_add_description_to_agenttransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='会话 ID (thread_id)', max_length=200, unique=True)),
                ('name', models.CharField(blank=True, default='', help_text='会话名称', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='是否为活跃会话')),
                ('message_count', models.IntegerField(default=0, help_text='消息数量')),
                ('last_message_preview', models.CharField(blank=True, default='', help_text='最后一条消息预览', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent 会话',
                'verbose_name_plural': 'Agent 会话',
                'ordering': ['-updated_at'],
            },
        ),
    ]
