# Generated by Django 5.2.4 on 2025-12-25 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_service', '0004_add_agent_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DialogStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='完整的对话风格模板')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dialog_style', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '对话风格',
                'verbose_name_plural': '对话风格',
            },
        ),
        migrations.CreateModel(
            name='SessionTodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='TODO 标题', max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='详细描述')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '进行中'), ('done', '已完成')], default='pending', help_text='状态', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='排序顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_items', to='agent_service.agentsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '会话 TODO',
                'verbose_name_plural': '会话 TODO',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionTodoSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_id', models.CharField(db_index=True, help_text='对应的对话检查点ID', max_length=100)),
                ('snapshot_data', models.TextField(help_text='JSON: 该检查点时刻的 TODO 列表完整状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_snapshots', to='agent_service.agentsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TODO 快照',
                'verbose_name_plural': 'TODO 快照',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="规则名称，如 '创建日程流程'", max_length=100)),
                ('trigger', models.CharField(help_text="触发条件描述，如 '当用户要求创建日程时'", max_length=200)),
                ('steps', models.TextField(help_text='纯文本步骤描述')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '工作流规则',
                'verbose_name_plural': '工作流规则',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="信息键，如 '姓名', '生日', '饮食偏好'", max_length=100)),
                ('value', models.TextField(help_text='信息值')),
                ('description', models.TextField(blank=True, default='', help_text='补充说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_infos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户个人信息',
                'verbose_name_plural': '用户个人信息',
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'key')},
            },
        ),
    ]
