# Generated by Django 5.2.4 on 2025-12-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_service', '0005_dialogstyle_sessiontodoitem_sessiontodosnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogstyle',
            name='custom_instructions',
            field=models.TextField(blank=True, default='', help_text='自定义指令'),
        ),
        migrations.AddField(
            model_name='dialogstyle',
            name='custom_languages',
            field=models.JSONField(blank=True, default=list, help_text='用户自定义的语言选项'),
        ),
        migrations.AddField(
            model_name='dialogstyle',
            name='custom_tones',
            field=models.JSONField(blank=True, default=list, help_text='用户自定义的语气选项'),
        ),
        migrations.AddField(
            model_name='dialogstyle',
            name='custom_verbosities',
            field=models.JSONField(blank=True, default=list, help_text='用户自定义的详细程度选项'),
        ),
        migrations.AddField(
            model_name='dialogstyle',
            name='language',
            field=models.CharField(choices=[('zh-CN', '简体中文'), ('en', 'English'), ('auto', '自动检测')], default='zh-CN', help_text='语言偏好', max_length=20),
        ),
        migrations.AddField(
            model_name='dialogstyle',
            name='tone',
            field=models.CharField(choices=[('neutral', '中性'), ('formal', '正式'), ('casual', '轻松'), ('professional', '专业'), ('friendly', '友好')], default='neutral', help_text='语气风格', max_length=20),
        ),
        migrations.AddField(
            model_name='dialogstyle',
            name='verbosity',
            field=models.CharField(choices=[('concise', '简洁'), ('normal', '适中'), ('detailed', '详细')], default='normal', help_text='详细程度', max_length=20),
        ),
        migrations.AlterField(
            model_name='dialogstyle',
            name='content',
            field=models.TextField(blank=True, help_text='完整的对话风格模板（自动生成）'),
        ),
    ]
