# Generated by Django 5.2.4 on 2025-12-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_service', '0006_dialogstyle_custom_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogstyle',
            name='memory_batch_size',
            field=models.IntegerField(default=20, help_text='记忆优化批次大小'),
        ),
    ]
