# Generated by Django 5.2.4 on 2025-12-30 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_service', '0007_dialogstyle_memory_batch_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroupCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_to_uuid', models.JSONField(default=dict, help_text='名称到UUID的映射')),
                ('uuid_to_info', models.JSONField(default=dict, help_text='UUID到完整信息的映射')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_group_cache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '日程组缓存',
                'verbose_name_plural': '日程组缓存',
            },
        ),
        migrations.CreateModel(
            name='SearchResultCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(help_text='event/todo/reminder/mixed', max_length=20)),
                ('index_mapping', models.JSONField(default=dict, help_text='编号到UUID的映射')),
                ('title_mapping', models.JSONField(default=dict, help_text='标题到UUID的映射')),
                ('query_params', models.JSONField(default=dict, help_text='查询参数')),
                ('checkpoint_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_caches', to='agent_service.agentsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_result_caches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '搜索结果缓存',
                'verbose_name_plural': '搜索结果缓存',
                'indexes': [models.Index(fields=['session', 'result_type'], name='agent_servi_session_acc44d_idx'), models.Index(fields=['session', 'updated_at'], name='agent_servi_session_f7ca56_idx')],
            },
        ),
    ]
