# Generated by Django 5.2.4 on 2026-01-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_service', '0008_eventgroupcache_searchresultcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogstyle',
            name='enable_context_optimization',
            field=models.BooleanField(default=True, help_text='是否启用 Agent 上下文优化（Token 管理、智能总结等）'),
        ),
    ]
