# Generated by Django 5.2.4 on 2026-01-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_service', '0009_dialogstyle_enable_context_optimization'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='is_summarizing',
            field=models.BooleanField(default=False, help_text='是否正在进行总结'),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='summary_created_at',
            field=models.DateTimeField(blank=True, help_text='总结创建时间', null=True),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='summary_text',
            field=models.TextField(blank=True, default='', help_text='对话历史总结文本'),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='summary_tokens',
            field=models.IntegerField(default=0, help_text='总结文本的 token 数'),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='summary_until_index',
            field=models.IntegerField(default=0, help_text='总结覆盖到的消息索引（不包含）'),
        ),
    ]
