# Generated by Django 5.2.4 on 2026-01-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_service', '0010_agentsession_is_summarizing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='summary_history',
            field=models.JSONField(blank=True, default=list, help_text='总结历史版本'),
        ),
    ]
