# Generated by Django 5.2.4 on 2026-01-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_service', '0012_add_naming_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsession',
            name='last_message_preview',
            field=models.CharField(blank=True, default='', help_text='最后一条消息预览（用户消息）', max_length=200),
        ),
    ]
