# Generated by Django 5.2.4 on 2026-01-31 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_service', '0013_add_naming_and_preview_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareGroupCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_to_id', models.JSONField(default=dict, help_text='名称到ID的映射')),
                ('id_to_info', models.JSONField(default=dict, help_text='ID到完整信息的映射')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_group_cache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '分享组缓存',
                'verbose_name_plural': '分享组缓存',
            },
        ),
    ]
