# Generated by Django 5.2.4 on 2026-02-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_service', '0014_sharegroupcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresultcache',
            name='next_index',
            field=models.IntegerField(default=1, help_text='下一个可用编号'),
        ),
        migrations.AddField(
            model_name='searchresultcache',
            name='uuid_to_index',
            field=models.JSONField(default=dict, help_text='UUID到编号的反向映射'),
        ),
    ]
