# Generated by Django 5.2.4 on 2026-02-03 16:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_service', '0015_add_smart_cache_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickActionTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_text', models.TextField(help_text='用户的快速操作指令', verbose_name='用户输入')),
                ('status', models.CharField(choices=[('pending', '等待执行'), ('processing', '执行中'), ('success', '成功'), ('failed', '失败'), ('timeout', '超时')], db_index=True, default='pending', help_text='任务执行状态', max_length=20)),
                ('result_type', models.CharField(blank=True, choices=[('action_completed', '操作完成'), ('need_clarification', '需要补充信息'), ('error', '错误')], help_text='结果类型：action_completed/need_clarification/error', max_length=30)),
                ('result', models.JSONField(blank=True, help_text='执行结果详情', null=True)),
                ('tool_calls', models.JSONField(default=list, help_text='工具调用记录')),
                ('agent_reasoning', models.TextField(blank=True, help_text='Agent 推理过程')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='开始执行时间', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='完成时间', null=True)),
                ('input_tokens', models.IntegerField(default=0, help_text='输入 token 数')),
                ('output_tokens', models.IntegerField(default=0, help_text='输出 token 数')),
                ('total_cost', models.FloatField(default=0.0, help_text='总成本 (CNY)')),
                ('model_used', models.CharField(blank=True, help_text='使用的模型名称', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_action_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '快速操作任务',
                'verbose_name_plural': '快速操作任务',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='agent_servi_user_id_ba25e2_idx'), models.Index(fields=['status', 'created_at'], name='agent_servi_status_cf17a0_idx')],
            },
        ),
    ]
