# Generated by Django 5.2.4 on 2026-02-10 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_service', '0016_add_quick_action_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='关联的 AgentSession.session_id', max_length=200)),
                ('type', models.CharField(choices=[('image', '图片'), ('pdf', 'PDF文档'), ('word', 'Word文档'), ('excel', 'Excel表格'), ('workflow', '工作流规则'), ('event', '日程事件'), ('todo', '待办事项'), ('reminder', '提醒')], help_text='附件类型', max_length=20)),
                ('filename', models.CharField(help_text='文件名或元素标题', max_length=255)),
                ('message_index', models.IntegerField(blank=True, help_text='附件被发送时的消息索引（LangGraph messages 数组索引）', null=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='发送时间', null=True)),
                ('file', models.FileField(blank=True, help_text='原始文件', null=True, upload_to='attachments/%Y/%m/%d/')),
                ('file_size', models.BigIntegerField(default=0, help_text='文件大小（字节）')),
                ('mime_type', models.CharField(blank=True, default='', help_text='MIME 类型', max_length=100)),
                ('thumbnail', models.ImageField(blank=True, help_text='缩略图', null=True, upload_to='attachments/thumbs/%Y/%m/%d/')),
                ('base64_data', models.TextField(blank=True, default='', help_text='Base64 编码的图片数据（用于 vision 模型）')),
                ('parsed_text', models.TextField(blank=True, default='', help_text='解析后的文本内容（OCR/文档提取，用于非 vision 模型）')),
                ('parse_status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', help_text='解析状态', max_length=20)),
                ('parse_error', models.TextField(blank=True, default='', help_text='解析错误信息')),
                ('internal_type', models.CharField(blank=True, default='', help_text='内部元素类型：event, todo, reminder, workflow', max_length=20)),
                ('internal_id', models.CharField(blank=True, default='', help_text='内部元素 ID（UserData JSON 中的 id 字段，或 WorkflowRule.id）', max_length=100)),
                ('internal_snapshot', models.JSONField(blank=True, default=dict, help_text='内部元素的快照数据（防止元素被删除后无法回溯）')),
                ('sent_as_format', models.CharField(blank=True, default='', help_text='实际发送格式：base64, text, markdown', max_length=20)),
                ('sent_with_model', models.CharField(blank=True, default='', help_text='发送时使用的模型 ID', max_length=100)),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已软删除')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='软删除时间', null=True)),
                ('deleted_with_message_index', models.IntegerField(blank=True, help_text='回滚时关联删除的消息索引', null=True)),
                ('deleted_reason', models.CharField(blank=True, default='', help_text='删除原因：rollback, manual, expired', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '会话附件',
                'verbose_name_plural': '会话附件',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', 'is_deleted'], name='agent_servi_session_df620e_idx'), models.Index(fields=['user', 'is_deleted'], name='agent_servi_user_id_f1cf3b_idx'), models.Index(fields=['deleted_at'], name='agent_servi_deleted_026e1e_idx')],
            },
        ),
    ]
