# Generated by Django 6.0.2 on 2026-02-17 08:50

import agent_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_service', '0017_sessionattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionattachment',
            name='file',
            field=models.FileField(blank=True, help_text='原始文件', null=True, upload_to=agent_service.models.attachment_upload_to),
        ),
    ]
