# Generated by Django 6.0.2 on 2026-02-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_service', '0018_alter_sessionattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='last_input_tokens',
            field=models.IntegerField(default=0, help_text='最近一次请求的 input_tokens（LLM 真实返回值）'),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='last_input_tokens_source',
            field=models.CharField(default='estimated', help_text='Token 数据来源: actual/estimated', max_length=20),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='last_input_tokens_updated_at',
            field=models.DateTimeField(blank=True, help_text='最近一次更新时间', null=True),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='summary_input_tokens',
            field=models.IntegerField(default=0, help_text='总结时的 input_tokens（LLM 真实返回值，用于上下文计算）'),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='summary_tokens_source',
            field=models.CharField(default='estimated', help_text='Token 数据来源: actual/estimated', max_length=20),
        ),
        migrations.AlterField(
            model_name='agentsession',
            name='summary_tokens',
            field=models.IntegerField(default=0, help_text='总结文本的 token 数（LLM 真实返回值）'),
        ),
    ]
