# Generated by Django 6.0.2 on 2026-02-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_service', '0019_agentsession_last_input_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='token_snapshots',
            field=models.JSONField(blank=True, default=dict, help_text='每轮对话的 Token 快照'),
        ),
    ]
