# Generated by Django 6.0.2 on 2026-03-12 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_service', '0020_agentsession_token_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='技能名称', max_length=100)),
                ('description', models.CharField(help_text='简短描述，供筛选器阅读以决定是否选用', max_length=500)),
                ('content', models.TextField(help_text='完整的技能内容，仅在被筛选器选中后注入 System Prompt')),
                ('is_active', models.BooleanField(default=True, help_text='是否进入筛选池')),
                ('source', models.CharField(choices=[('manual', '手动创建'), ('ai', 'AI 生成'), ('imported', '外部导入')], default='manual', help_text='来源', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent 技能',
                'verbose_name_plural': 'Agent 技能',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
