# Generated by Django 6.0.2 on 2026-03-14 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_service', '0021_add_agentskill_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentStateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('phase', models.CharField(default='idle', help_text='当前任务阶段', max_length=50)),
                ('active_skills', models.JSONField(default=list, help_text='激活的技能 ID 列表')),
                ('focus_files', models.JSONField(default=list, help_text='关注的文件路径列表')),
                ('accumulated_findings', models.JSONField(default=list, help_text='累积发现列表')),
                ('pending_tasks', models.JSONField(default=list, help_text='待处理任务列表')),
                ('tool_results_summary', models.JSONField(default=list, help_text='工具结果摘要列表')),
                ('last_user_message', models.TextField(blank=True, default='', help_text='上一轮用户消息摘要')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='额外元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent 状态快照',
                'verbose_name_plural': 'Agent 状态快照',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessagePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_index', models.IntegerField(db_index=True)),
                ('part_type', models.CharField(choices=[('text', '文本'), ('tool', '工具调用'), ('file', '文件'), ('reasoning', '推理过程')], db_index=True, max_length=20)),
                ('content', models.TextField(blank=True, default='')),
                ('tool_name', models.CharField(blank=True, default='', max_length=100)),
                ('tool_input', models.JSONField(blank=True, default=dict)),
                ('tool_output', models.TextField(blank=True, default='')),
                ('tool_status', models.CharField(blank=True, choices=[('pending', '等待中'), ('success', '成功'), ('error', '失败')], default='', max_length=20)),
                ('file_ref', models.CharField(blank=True, default='', max_length=500)),
                ('file_type', models.CharField(blank=True, default='', max_length=50)),
                ('role', models.CharField(default='', max_length=20)),
                ('checkpoint_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '消息分片',
                'verbose_name_plural': '消息分片',
                'ordering': ['session', 'message_index', 'part_type'],
            },
        ),
        migrations.AddField(
            model_name='agenttransaction',
            name='checkpoint_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='检查点 ID', max_length=100),
        ),
        migrations.AddField(
            model_name='agenttransaction',
            name='duration_ms',
            field=models.IntegerField(blank=True, help_text='执行时长（毫秒）', null=True),
        ),
        migrations.AddField(
            model_name='agenttransaction',
            name='message_index',
            field=models.IntegerField(blank=True, db_index=True, help_text='关联的消息索引', null=True),
        ),
        migrations.AddField(
            model_name='agenttransaction',
            name='reversible',
            field=models.BooleanField(default=True, help_text='是否可回滚'),
        ),
        migrations.AddField(
            model_name='agenttransaction',
            name='rollback_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='回滚所需的元数据'),
        ),
        migrations.AddField(
            model_name='agenttransaction',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', '等待中'), ('success', '成功'), ('error', '失败')], default='', help_text='执行状态', max_length=20),
        ),
        migrations.AddField(
            model_name='agenttransaction',
            name='tool_input_hash',
            field=models.CharField(blank=True, default='', help_text='输入哈希', max_length=64),
        ),
        migrations.AddField(
            model_name='agenttransaction',
            name='tool_source',
            field=models.CharField(blank=True, default='', help_text='工具来源标识', max_length=100),
        ),
        migrations.AddField(
            model_name='agenttransaction',
            name='tool_type',
            field=models.CharField(choices=[('native', '原生工具'), ('mcp', 'MCP 工具'), ('external', '外部服务')], default='native', help_text='工具类型', max_length=20),
        ),
        migrations.AddIndex(
            model_name='agenttransaction',
            index=models.Index(fields=['session_id', 'checkpoint_id'], name='agent_servi_session_d6542f_idx'),
        ),
        migrations.AddIndex(
            model_name='agenttransaction',
            index=models.Index(fields=['session_id', 'tool_type'], name='agent_servi_session_1089a2_idx'),
        ),
        migrations.AddField(
            model_name='agentstatesnapshot',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_snapshots', to='agent_service.agentsession'),
        ),
        migrations.AddField(
            model_name='agentstatesnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_state_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagepart',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_parts', to='agent_service.agentsession'),
        ),
        migrations.AddField(
            model_name='messagepart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_parts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='messagepart',
            index=models.Index(fields=['session', 'message_index'], name='agent_servi_session_c9f20d_idx'),
        ),
        migrations.AddIndex(
            model_name='messagepart',
            index=models.Index(fields=['session', 'checkpoint_id'], name='agent_servi_session_79c971_idx'),
        ),
    ]
