# Generated by Django 6.0.2 on 2026-03-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_service', '0021_add_agentskill_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='state_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Agent 状态快照，最多保留 10 个历史版本'),
        ),
    ]
