# Generated by Django 6.0.2 on 2026-03-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_service', '0022_add_state_snapshot_to_agentsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='last_llm_request_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='最近一次 LLM 请求的完整序列化快照（用于前端可视化调试）'),
        ),
    ]
