# Generated by Django 6.0.2 on 2026-03-28 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_service', '0024_agentsession_summary_trigger_count'),
        ('file_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionattachment',
            name='cloud_file',
            field=models.ForeignKey(blank=True, help_text='关联的云盘文件（从云盘加载时设置）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_references', to='file_service.userfile'),
        ),
    ]
