# Generated by Django 6.0.2 on 2026-05-23 13:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_service', '0026_sessionattachment_ocr_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('month', models.CharField(db_index=True, max_length=7)),
                ('call_site', models.CharField(db_index=True, default='main_agent', max_length=50)),
                ('model_id', models.CharField(db_index=True, max_length=100)),
                ('model_name', models.CharField(blank=True, default='', max_length=200)),
                ('provider', models.CharField(blank=True, default='', max_length=50)),
                ('style', models.CharField(blank=True, default='', max_length=50)),
                ('is_system_model', models.BooleanField(default=True)),
                ('input_total_tokens', models.IntegerField(default=0)),
                ('input_cache_miss_tokens', models.IntegerField(default=0)),
                ('input_cache_hit_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('reasoning_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('cache_hit_ratio', models.FloatField(default=0.0)),
                ('price_input_cache_miss_per_1k', models.FloatField(default=0.0)),
                ('price_input_cache_hit_per_1k', models.FloatField(default=0.0)),
                ('price_output_per_1k', models.FloatField(default=0.0)),
                ('cost_input_cache_miss', models.FloatField(default=0.0)),
                ('cost_input_cache_hit', models.FloatField(default=0.0)),
                ('cost_output', models.FloatField(default=0.0)),
                ('cost_total', models.FloatField(default=0.0)),
                ('currency', models.CharField(default='CNY', max_length=10)),
                ('source', models.CharField(default='actual', max_length=20)),
                ('diagnostics', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_records', to='agent_service.agentsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_usage_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent 用量明细',
                'verbose_name_plural': 'Agent 用量明细',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'month'], name='agent_servi_user_id_6b0c7b_idx'), models.Index(fields=['user', 'model_id'], name='agent_servi_user_id_2ae2b9_idx'), models.Index(fields=['user', 'call_site'], name='agent_servi_user_id_a8744d_idx'), models.Index(fields=['user', 'created_at'], name='agent_servi_user_id_33f14f_idx')],
            },
        ),
    ]
