# Generated by Django 5.2.4 on 2025-12-03 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reversion', '0002_add_index_on_version_for_content_type_and_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='LangGraph Session ID', max_length=255)),
                ('action_type', models.CharField(help_text='操作类型 (例如: create_event)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='操作的人类可读描述')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_reverted', models.BooleanField(default=False)),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reversion.revision')),
            ],
        ),
    ]
