# Generated by Django 5.2.4 on 2025-12-03 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentTransaction',
        ),
    ]
